### PR TITLE
Use standard C method (#include) for including the array/switch.

### PR DESCRIPTION
**Pull request by alejandro-colomar**

### CODE REVIEW

**Comment by mentalisttraceur** [comment]
My inclination is to decline this, but:

1. You might be seeing some use cases or benefits or downsides that I'm not seeing. So I'd really like to hear how the existing way was bad for you, what friction points it caused, or what it got in the way of? (This might change my mind, or this might help us come up with other improvements that work just as well or better for you and others!)

2. I'll try to figure out and explain why I prefer the current way in a follow-up comment, and I am open to being convinced that I'm wrong!

3. Either way, I really appreciate your contribution! It is nice to see that you cared enough about my little library to improve it!

**Comment by mentalisttraceur** [comment]
Before I get into what I prefer about the current way, I want to acknowledge every benefit I see of doing it this pull request's way. If you see any benefits you think I didn't cover, let me know! (I might edit benefits as I figure them out into this comment, so that new readers who come later can see them all in one place.)

1. Easier to look at the "template" of `errnoname.c`. We can read and understand the template without mentally "switching out of" C. Tooling has an easier time detecting and treating it as C.

2. If someone is using C, they can be expected to grok `#include`, but they might not have ever encountered any of the template languages which use `{{ ... }}` .

3. Even if someone is familiar with a `{{ ... }}`-style template language, the current way uses a manual implementation of a very hardcoded, very limited way of doing it, using some cryptic shell commands, which I have seen first-hand is hard for many people to figure out.

4. If someone wants to copy/"vendor" `errnoname` into their own project, this is probably better for most people who would be *looking at* and *trying to understand* `errnoname.c` inside that project's code.

**Comment by mentalisttraceur** [comment]
Okay, now what I like about the current way:

1. Right now my non-standard templating solution seems weird because `errnoname` only provides a C library, but I want to maintain readiness to add support for other programming languages as the need arises. Imagine multiple `errnoname.{{ language }}.template` files, all of which have `{{ some_appropriate_name }}` somewhere in them, and corresponding `generate-{{ language }}.sh` files which use the same exact technique to weave the generated code into the code template.

    A good question to ask here: am I [prematurely abstracting](https://softwareengineering.stackexchange.com/a/420712)? I've seriously considered this, because there is a good argument to be made that until I actually *do* support another language that justifies the above, it is premature to expect that this abstracted not-standard-C way of doing it is justified. We can discuss this more in-depth if anyone wants to get into it. 

2. Currently, the C library parts of this repo are two files: `errnoname.h` and `errnoname.c`. `errnoname.h` is completely self-contained, and `errnoname.c` only depends on the standard `<errno.h>`, so it's effectively self-contained to the extent that such a simple standard header can be assumed to exist. `errnoname.c` even contains include guards, because I want to support statically including all of `errnoname.c` in the same translation unit as other code (projects like SQLite prove that bundling a lot of code into one translation unit can have real and significant benefits, and link-time optimization across separate translation units is necessarily a harder problem than making the same optimizations in the same C translation unit.)

    I realize it's not a big deal to have to copy and keep two extra ".c.include" files and to ensure that they're in the right paths to be found by the `#include`, but I feel that a library like `errnoname` benefits if you can just drop `errnoname.c` into some folder instead of multiple files. I can confirm that I personally feel better knowing that I can do that, especially in small command-line utilities that I might write.
    
    Also, the current way takes the "how to glue all the generated C code together with the template?" question and deals with it as a pre-build step in a way that perfectly isolates it from a developer who just wants to build or use the C library. This PR's way kinda "pops" that bubble, spills the "gluing of generated C code together with the template" out into the build step. This feels a little wrong to me - the same mental feel as when something improperly leaks across an abstraction/interface boundary.

     Basically, all ".c" files that have to be present to build the library are - in a sense - part of the "public interface" of a C library. Not to the same extent as the actual API - the publicly exported symbols. But if someone is vendoring the library into their project, or if they want to build the library from source, then it effects them - they have to know about it and deal with it. And I feel resistant expanding/complicating that surface area beyond just one `errnoname.c` file (that isn't to say I'm categorically against contributions which cause builds to require multiple ".c" files - for example, I'd feel more receptive to it if someone wanted to add new functionality *and* there was a good argument that this new functionality should be separated from the "core" `errnoname.c` file.)

**Comment by alejandro-colomar** [comment]
> My inclination is to decline this, but:
> 
>     1. You might be seeing some use cases or benefits or downsides that I'm not seeing. So I'd really like to hear how the existing way was bad for you, what friction points it caused, or what it got in the way of? (This might change my mind, or this might help us come up with other improvements that work just as well or better for you and others!)
> 
>     2. I'll try to figure out and explain why I prefer the current way in a follow-up comment, and I am open to being convinced that I'm wrong!
> 
>     3. Either way, I really appreciate your contribution! It is nice to see that you cared enough about my little library to improve it!

Thank you for creating this library!

I'll try to answer all of your questions one by one.

BTW, I requested the inclusion of this feature in glibc yesterday[1], and surprise: they added it a few months ago (in glibc 2.32)[2].  I already updated the StackOverflow question about this[3].  Actually, I should've known about it before, as comaintainer of the man-pages, but I forgot it existed[4] (for the next release, I fixed VERSIONS to say that it was added in glibc 2.32) :-).


[1]: <https://sourceware.org/bugzilla/show_bug.cgi?id=27430>
[2]: <https://www.gnu.org/software/libc/manual/html_node/Error-Messages.html>
[3]: <https://stackoverflow.com/a/66237250/6872717>
[4]: <https://man7.org/linux/man-pages/man3/strerrorname_np.3.html>

**Comment by alejandro-colomar** [comment]
> Before I get into what I prefer about the current way, I want to acknowledge every benefit I see of doing it this pull request's way. If you see any benefits you think I didn't cover, let me know! (I might edit benefits as I figure them out into this comment, so that new readers who come later can see them all in one place.)
> 
>     1. Easier to look at the "template" of `errnoname.c`. We can read and understand the template without mentally "switching out of" C. Tooling has an easier time detecting and treating it as C.

Yes!

> 
>     2. If someone is using C, they can be expected to grok `#include`, but they might not have ever encountered any of the template languages which use `{{ ... }}` .

Yes! (I have seen `#include` since I can remember, but only found `{{ ... }}` a short time ago :-))

> 
>     3. Even if someone is familiar with a `{{ ... }}`-style template language, the current way uses a manual implementation of a very hardcoded, very limited way of doing it, using some cryptic shell commands, which I have seen first-hand is hard for many people to figure out.

This one is not so important (at least to me).  If it works, and uses an understandable syntax, it's good.  I would probably have understood it, even if I had never seen `{{ ... }}` before.

> 
>     4. If someone wants to copy/"vendor" `errnoname` into their own project, this is probably better for most people who would be _looking at_ and _trying to understand_ `errnoname.c` inside that project's code.

Yes.  Before knowing that glibc provides `strerrorname_np()` I was thinking of adding this to my library, and I would prefer to add 3 .c files than adding the template and some script.  It already has some hundreds of .c files, so a few more won't hurt :-)

**Comment by alejandro-colomar** [comment]
> Okay, now what I like about the current way:
> 
>     1. Right now my non-standard templating solution seems weird because `errnoname` only provides a C library, but I want to maintain readiness to add support for other programming languages as the need arises. Imagine multiple `errnoname.{{ language }}.template` files, all of which have `{{ some_appropriate_name }}` somewhere in them, and corresponding `generate-{{ language }}.sh` files which use the same exact technique to weave the generated code into the code template.

I would do it in a different way:  Write a wrapper function that calls your C function.  I know this is what is usually done in python where they somehow call C / C++ functions (I know it's possible, but I've never done it, so I can't help).

>        A good question to ask here: am I [prematurely abstracting](https://softwareengineering.stackexchange.com/a/420712)? I've seriously considered this, because there is a good argument to be made that until I actually _do_ support another language that justifies the above, it is premature to expect that this abstracted not-standard-C way of doing it is justified. We can discuss this more in-depth if anyone wants to get into it.

As I said above, I think you are.  I would write wrappers for any language that needs it, instead of writing a native function for each language, which as you say, would include the burden of creating the list in each of them.

> 
>     2. Currently, the C library parts of this repo are two files: `errnoname.h` and `errnoname.c`. `errnoname.h` is completely self-contained, and `errnoname.c` only depends on the standard `<errno.h>`, so it's effectively self-contained to the extent that such a simple standard header can be assumed to exist. `errnoname.c` even contains include guards, because I want to support statically including all of `errnoname.c` in the same translation unit as other code (projects like SQLite prove that bundling a lot of code into one translation unit can have real and significant benefits, and link-time optimization across separate translation units is necessarily a harder problem than making the same optimizations in the same C translation unit.)

Yes, simplicity is a big point.

However, the following occurs to me:
If you only have the C function (all other languages having wrappers around it), you can use `#include`, and still have this behavior.  You would only need to use the script to replace `#include "errnoname.*\.c\.inc" by the contents of the file, which would allow both kinds of usage (having many C files that include normally, or have a single C file).

>        I realize it's not a big deal to have to copy and keep two extra ".c.include" files and to ensure that they're in the right paths to be found by the `#include`, but I feel that a library like `errnoname` benefits if you can just drop `errnoname.c` into some folder instead of multiple files. I can confirm that I personally feel better knowing that I can do that, especially in small command-line utilities that I might write.

Yes, simplicity is always a good reason.  However, your script could do that with `#include` too, as I said above.

>        Also, the current way takes the "how to glue all the generated C code together with the template?" question and deals with it as a pre-build step in a way that perfectly isolates it from a developer who just wants to build or use the C library. This PR's way kinda "pops" that bubble, spills the "gluing of generated C code together with the template" out into the build step. This feels a little wrong to me - the same mental feel as when something improperly leaks across an abstraction/interface boundary.

You can still build the library object code separately to the build of the project.  So it depends on how you set up your Makefile.  In the end you'll only have a single .o file.

>        Basically, all ".c" files that have to be present to build the library are - in a sense - part of the "public interface" of a C library. Not to the same extent as the actual API - the publicly exported symbols. But if someone is vendoring the library into their project, or if they want to build the library from source, then it effects them - they have to know about it and deal with it. And I feel resistant expanding/complicating that surface area beyond just one `errnoname.c` file (that isn't to say I'm categorically against contributions which cause builds to require multiple ".c" files - for example, I'd feel more receptive to it if someone wanted to add new functionality _and_ there was a good argument that this new functionality should be separated from the "core" `errnoname.c` file.)

**Comment by alejandro-colomar** [comment]
> However, the following occurs to me:
> If you only have the C function (all other languages having wrappers around it), you can use `#include`, and still have this behavior. You would only need to use the script to replace `#include "errnoname.*.c.inc" by the contents of the file, which would allow both kinds of usage (having many C files that include normally, or have a single C file).



````
function sed_include()
{
	# Requires the filename of the file to include as its argument
	sed '\%#include "'"${1}"'"% {
		r '"${1}"'
		d
	}';
}
````

The function above may help you.

I remember having learnt that function from here: <https://grymoire.com/Unix/Sed.html>

**Comment by mentalisttraceur** [comment]
Okay, thank you for your thoughts! I'll think it over some more and get back to this as soon as I have a conclusion.

I might post more comments in here as I "think out loud" about this. I might also create a publicly visible branch to play around with the `#include`-based way. You are of course welcome to reply to any of that in here.

**Comment by mentalisttraceur** [comment]
I have one quick question in the meantime. You said:

> Yes. Before knowing that glibc provides `strerrorname_np()` I was thinking of adding this to my library, and I would prefer to add 3 .c files than adding the template and some script.

But would you prefer to add 3 .c files rather than the 1 .c file? Because you don't _need_ to add the script: the `errnoname.c` is already generated for you.

My point was about the 3 .c files being in some ways clearer than the 1 .c file. But your agreement seems to be about the 3 .c files versus the .c.template file and generation script, so now I'm not sure if we're on the same page.

Here's another way to get at the heart of what I'm curious about: imagine that this repo didn't even have the script, nor the template file. If the repo just looked like this:

```
LICENSE
README.md
errnoname.c
errnoname.h
```

would you have just happily copied the `errnoname.c`, into your project? Or would you have thought "I'd like to pull the array and switch entries into separate files, so I and others who look at my repo can see the logic of the `errnoname` function more clearly?

**Comment by alejandro-colomar** [comment]
> I have one quick question in the meantime. You said:
> 
> > Yes. Before knowing that glibc provides `strerrorname_np()` I was thinking of adding this to my library, and I would prefer to add 3 .c files than adding the template and some script.
> 
> But would you prefer to add 3 .c files rather than the 1 .c file? Because you don't _need_ to add the script: the `errnoname.c` is already generated for you.
> 
> My point was about the 3 .c files being in some ways clearer than the 1 .c file. But your agreement seems to be about the 3 .c files versus the .c.template file and generation script, so now I'm not sure if we're on the same page.

You're right.  I forgot I don't need the script anymore. I'd either copy the script in both cases, or neither.

> 
> Here's another way to get at the heart of what I'm curious about: imagine that this repo didn't even have the script, nor the template file. If the repo just looked like this:
> 
> ```
> LICENSE
> README.md
> errnoname.c
> errnoname.h
> ```
> 
> would you have just happily copied the `errnoname.c`, into your project? Or would you have thought "I'd like to pull the array and switch entries into separate files, so I and others who look at my repo can see the logic of the `errnoname` function more clearly?

I'd still use the .inc files. As you say, having a huge list in a .c file makes it more difficult to follow.  I think I'd still use the .inc files, but would understand 1 file as a simpler option in some cases.

**Comment by mentalisttraceur** [comment]
Verdict:

1. I will provide the split `errnoname.c`, `errnoname-switch-cases.c.inc`, and `errnoname-array-entries.c.inc` files, because I relate to and sympathize with the desire to vendor `errnoname` in a form that has the readability of the template but is ready-to-use without extra non-C build steps.

2. I will still provide a *combined* `errnoname.c`, because I relate to and sympathize with the preference to vendor `errnoname` with minimal hassle and obtrusiveness over the vendored copy being nice to examine.

3. The combined file will still have "center stage", but both variants will be officially supported. Examples of what this means:

    1. The `errnoname.h` and the *combined* `errnoname.c` files will reside at the top level of this repo.

    2. The split files will reside in a subfolder. I will try to name this folder something reasonably self-descriptive, like `variant-for-readable-vendoring/`. I will also put a small README into that subfolder, to help explain why it's there or what it's good for.

    3. If at some point I provide a Makefile, VSCode project file, or any other build-helper stuff, it will not go out of its way to "reach into" that folder - if someone wants to build the split version using those helpers, they can move those three files back up to the top.

    4. If at some point I realize that the tyranny of giving people options is causing this library to lose users by causing confusion or indecision or whatever, and I have to try to deemphasize or drop one alternative, the split file alternative will get "the short end of the stick". (But I'd treat dropping support for it, or changing where the files reside, as seriously as any other change which might break someone's automated builds which expect the files to be at the current paths.)

    5. The top-level README will probably only mention the alternative briefly or not at all. 

---

Implementation thoughts:

* You don't have to do anything for this. I've got a burst of changes planned for this repo anyway, and I'll re-implement this as part of that activity on top of those changes. This isn't anything personal, it's just smoother/easier/faster for me that way: I've got other changes "in flight" and I have slight differences to exactly how I want it done, which would cause a rewrite of every line anyway, so I might as well do it myself instead of making you do it.

* I will generate the combined `errnoname.c` from the split files, so the `errnoname.c.template` file will be deleted, and the split `errnoname.c` will become the actual "source of truth"/"template" for the combined variant.

* I will change `generate-c.sh` to generate the `errnoname-*.c.inc` files, similarly to how this pull request currently does it.

* I will add a `combine-c.sh` script which will combine the split files into the combined file.

* When I'm finished re-implementing what you want per the above, I'll close this pull-request.

**Comment by mentalisttraceur** [comment]
Okay! Implemented in commit 001bb073483ccb0f1f58d645bc7907b2112c4e5e!

**Comment by mentalisttraceur** [comment]
Btw, I wanted to give you credit in the repo history for your contribution, even though I didn't actually merge your code, so I put this at the end of that commit's message:

> Special thanks to Alejandro Colomar <alx.manpages@gmail.com> for
> 1. suggesting the alternative using `#include` and `.inc` files,
> 2. providing an example implementation of that alternative, and
> 3. arguing for it convincingly enough to get me to do it.

**Comment by alejandro-colomar** [comment]
> Btw, I wanted to give you credit in the repo history for your contribution, even though I didn't actually merge your code, so I put this at the end of that commit's message:
> 
> > Special thanks to Alejandro Colomar [alx.manpages@gmail.com](mailto:alx.manpages@gmail.com) for
> > 
> > 1. suggesting the alternative using `#include` and `.inc` files,
> > 2. providing an example implementation of that alternative, and
> > 3. arguing for it convincingly enough to get me to do it.

Thanks!  It's looking good. :-)

**Pull request closed without merging**
